apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging-demo
  namespace: gepaplexx-cicd-tools
  labels:
    owner: gepaplexx
    scope: demo
spec:
  description: ArgoCD Project to deploy a sample application to showcase our staging concept
  # Allow manifests to deploy only from this repositories
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

