apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-demo
  labels:
    owner: gepaplexx
    scope: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: gepaplexx-cicd-tools
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
            branch: dev
          - cluster: qa
            url: https://kubernetes.default.svc
            branch: qa
          - cluster: prod
            url: https://kubernetes.default.svc
            branch: prod
          # - cluster: feature-gpx-500
          #   url: https://kubernetes.default.svc
          #   branch: main
          - cluster: feature-gpx-501
            url: https://kubernetes.default.svc
            branch: main
  template:
    metadata:
      name: 'staging-demo-{{cluster}}'
    spec:
      project: staging-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: git@github.com:gepaplexx-demos/staging-concept-demo.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: apps/env/{{ cluster }}
      destination:
        server: '{{url}}'
        namespace: 'staging-demo-{{cluster}}'
