apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-demo-dev
  labels:
    owner: gepaplexx
    scope: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: gepaplexx-cicd-tools
spec:
  generators:
    - list:
        elements:
          - cluster: feature-gpx-500
            url: https://kubernetes.default.svc
          - cluster: feature-gpx-501
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'staging-demo-{{cluster}}'
    spec:
      project: staging-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: https://gitlab.com/sokube-io/product-demo/gitops-kustomize-helm-sample.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: 'main'
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: apps/env/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: 'staging-demo-{{cluster}}'
