---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraping-gepardenblick
  labels:
    required-hotfix: prod
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /q/metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: gepardenblick
